### ISSUE TITLE
One Suggestion from an old pall for Builder Pattern

### ISSUE THREAD

**Issue by TasosTilsi** [vpetrou/test-automation-patterns#1]
[Here](https://github.com/vpetrou/test-automation-patterns/tree/master/creational/builder/src/main/java/com/vpetrou/dev/patterns/creational/builder) in builder pattern there is no need to write two separate classes, you can use the annotation @ Builder from Lombok library in the User class, so automatically you can use the builder pattern if you want or use it as usual. :) 

I bet that you know that but just in case! <3

**Comment by vpetrou** [comment]
> [Here](https://github.com/vpetrou/test-automation-patterns/tree/master/creational/builder/src/main/java/com/vpetrou/dev/patterns/creational/builder) in builder pattern there is no need to write two separate classes, you can use the annotation @ Builder from Lombok library in the User class, so automatically you can use the builder pattern if you want or use it as usual. :)
> 
> I bet that you know that but just in case! <3

My old pal and great mind Taso you are so right!
I do have examples with lombok @Builder etc.
An indicative [here](src/main/java/com/vpetrou/cs/model/Contact.java).

You know there are so many opinions regarding lombok, hidden implementations and not-needed code that it generates, plus the code coverage calculations that made me follow various strategies per case.

For sure, I fully agree with your point but I will keep it as is, for an academic point of view. One step further is exactly the approach you describe. 
Thank you so much for the comment mate!
